"use client";
import Container from "@mui/material/Container";
import Typography from "@mui/material/Typography";
import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import MuiLink from "@mui/material/Link";
import { useTranslation } from "@/services/i18n/client";

function PrivacyPolicy() {
  const { t } = useTranslation("privacy-policy");
  return (
    <Container maxWidth="md" sx={{ py: 8 }}>
      <Typography
        variant="h2"
        component="h1"
        data-testid="privacy-policy-title"
        gutterBottom
        sx={{ fontWeight: "bold" }}
      >
        {t("title")}
      </Typography>
      <Typography gutterBottom paragraph>
        Last updated: May 16, 2024
      </Typography>
      <Typography
        data-testid="privacy-policy-description"
        gutterBottom
        paragraph
      >
        {t("description-1")}
      </Typography>
      <Typography gutterBottom paragraph>
        {t("description-2")}
      </Typography>
      <Typography
        component="h2"
        variant="h3"
        letterSpacing="-0.02em"
        gutterBottom
        sx={{
          mt: 7,
        }}
      >
        Interpretation and Definitions
      </Typography>
      <Typography
        component="h3"
        variant="h4"
        gutterBottom
        sx={{
          mt: 5,
        }}
      >
        Interpretation
      </Typography>
      <Typography gutterBottom paragraph>
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </Typography>
      <Typography
        component="h3"
        variant="h4"
        gutterBottom
        sx={{
          mt: 5,
        }}
      >
        Definitions
      </Typography>
      <Typography gutterBottom paragraph>
        For the purposes of this Privacy Policy:
      </Typography>
      <List sx={{ listStyleType: "disc", pl: 5, mb: 6 }}>
        <ListItem sx={{ display: "list-item" }}>
          <strong>Account</strong> means a unique account created for You to
          access our Service or parts of our Service.
        </ListItem>
        <ListItem sx={{ display: "list-item" }}>
          <strong>Affiliate</strong> means an entity that controls, is
          controlled by or is under common control with a party, where
          &quot;control&quot; means ownership of 50% or more of the shares,
          equity interest or other securities entitled to vote for election of
          directors or other managing authority.
        </ListItem>
        <ListItem sx={{ display: "list-item" }}>
          <strong>Company</strong> (referred to as either &quot;the
          Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in
          this Agreement) refers to BC Boilerplates
        </ListItem>
        <ListItem sx={{ display: "list-item" }}>
          <strong>Cookies</strong>are small files that are placed on Your
          computer, mobile device or any other device by a website, containing
          the details of Your browsing history on that website among its many
          uses.
        </ListItem>
        <ListItem sx={{ display: "list-item" }}>
          <strong>Device</strong> means any device that can access the Service
          such as a computer, a cellphone or a digital tablet.
        </ListItem>
        <ListItem sx={{ display: "list-item" }}>
          <strong>Personal Data</strong> is any information that relates to an
          identified or identifiable individual.
        </ListItem>
        <ListItem sx={{ display: "list-item" }}>
          <strong>Service</strong> refers to the Website.
        </ListItem>
        <ListItem sx={{ display: "list-item" }}>
          <strong>Service Provider</strong> means any natural or legal person
          who processes the data on behalf of the Company. It refers to
          third-party companies or individuals employed by the Company to
          facilitate the Service, to provide the Service on behalf of the
          Company, to perform services related to the Service or to assist the
          Company in analyzing how the Service is used.
        </ListItem>
        <ListItem sx={{ display: "list-item" }}>
          <strong>Usage Data</strong> refers to data collected automatically,
          either generated by the use of the Service or from the Service
          infrastructure itself (for example, the duration of a page visit).
        </ListItem>
        <ListItem sx={{ display: "list-item" }}>
          <strong>Website</strong> refers to Extensive React Boilerplate,
          accessible from{" "}
          <MuiLink
            target="_blank"
            rel="external noopener noreferrer"
            href="https://react-boilerplate-coral.vercel.app/en"
          >
            https://react-boilerplate-coral.vercel.app/en
          </MuiLink>
        </ListItem>
        <ListItem sx={{ display: "list-item" }}>
          <strong>You</strong> means the individual accessing or using the
          Service, or the company, or other legal entity on behalf of which such
          individual is accessing or using the Service, as applicable.
        </ListItem>
      </List>
      <Typography
        component="h2"
        variant="h3"
        gutterBottom
        letterSpacing="-0.02em"
      >
        Collecting and Using Your Personal Data
      </Typography>
      <Typography
        component="h3"
        variant="h4"
        sx={{
          my: 5,
        }}
      >
        Types of Data Collected
      </Typography>
      <Typography component="h4" variant="h5" gutterBottom>
        Personal Data
      </Typography>
      <Typography gutterBottom paragraph>
        While using Our Service, We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information may include, but is
        not limited to:
      </Typography>
      <List sx={{ listStyleType: "disc", pl: 5, mb: 3 }}>
        <ListItem sx={{ display: "list-item" }}>Usage Data</ListItem>
      </List>
      <Typography component="h4" variant="h5" gutterBottom>
        Usage Data
      </Typography>
      <Typography gutterBottom paragraph>
        Usage Data is collected automatically when using the Service.
      </Typography>
      <Typography gutterBottom paragraph>
        When You access the Service by or through a mobile device, We may
        collect certain information automatically, including, but not limited
        to, the type of mobile device You use, Your mobile device unique ID, the
        IP address of Your mobile device, Your mobile operating system, the type
        of mobile Internet browser You use, unique device identifiers and other
        diagnostic data.
      </Typography>
      <Typography gutterBottom paragraph>
        We may also collect information that Your browser sends whenever You
        visit our Service or when You access the Service by or through a mobile
        device.
      </Typography>
      <Typography component="h4" variant="h5" gutterBottom sx={{ mt: 5 }}>
        Tracking Technologies and Cookies
      </Typography>
      <Typography gutterBottom paragraph>
        We use Cookies and similar tracking technologies to track the activity
        on Our Service and store certain information. Tracking technologies used
        are beacons, tags, and scripts to collect and track information and to
        improve and analyze Our Service. The technologies We use may include:
      </Typography>
      <List sx={{ listStyleType: "disc", pl: 5 }}>
        <ListItem sx={{ display: "list-item" }}>
          <strong>Cookies or Browser Cookies.</strong> A cookie is a small file
          placed on Your Device. You can instruct Your browser to refuse all
          Cookies or to indicate when a Cookie is being sent. However, if You do
          not accept Cookies, You may not be able to use some parts of our
          Service. Unless you have adjusted Your browser setting so that it will
          refuse Cookies, our Service may use Cookies.
        </ListItem>
        <ListItem sx={{ display: "list-item" }}>
          <strong>Web Beacons.</strong> Certain sections of our Service and our
          emails may contain small electronic files known as web beacons (also
          referred to as clear gifs, pixel tags, and single-pixel gifs) that
          permit the Company, for example, to count users who have visited those
          pages or opened an email and for other related website statistics (for
          example, recording the popularity of a certain section and verifying
          system and server integrity).
        </ListItem>
      </List>
      <Typography gutterBottom paragraph>
        Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies.
        Persistent Cookies remain on Your personal computer or mobile device
        when You go offline, while Session Cookies are deleted as soon as You
        close Your web browser. Learn more about cookies on the Free Privacy
        Policy website article.
      </Typography>
      <Typography gutterBottom paragraph>
        We use both Session and Persistent Cookies for the purposes set out
        below:
      </Typography>
      <List sx={{ listStyleType: "disc", pl: 5 }}>
        <ListItem sx={{ display: "list-item" }}>
          <Typography gutterBottom paragraph sx={{ fontWeight: "bold" }}>
            Necessary / Essential Cookies
          </Typography>
          <Typography gutterBottom paragraph>
            Type: Session Cookies
          </Typography>
          <Typography gutterBottom paragraph>
            Administered by: the Company
          </Typography>
          <Typography gutterBottom paragraph>
            Purpose: These Cookies are essential to provide You with services
            available through the Website and to enable You to use some of its
            features. They help to authenticate users and prevent fraudulent use
            of user accounts. Without these Cookies, the services that You have
            asked for cannot be provided, and We only use these Cookies to
            provide You with those services.
          </Typography>
        </ListItem>
        <ListItem sx={{ display: "list-item" }}>
          <Typography gutterBottom paragraph sx={{ fontWeight: "bold" }}>
            Cookies Policy / Notice Acceptance Cookies
          </Typography>
          <Typography gutterBottom paragraph>
            Type: Persistent Cookies
          </Typography>
          <Typography gutterBottom paragraph>
            Administered by: the Company
          </Typography>
          <Typography gutterBottom paragraph>
            Purpose: These Cookies identify if users have accepted the use of
            cookies on the Website.
          </Typography>
        </ListItem>
        <ListItem sx={{ display: "list-item" }}>
          <Typography gutterBottom paragraph sx={{ fontWeight: "bold" }}>
            Functionality Cookies
          </Typography>
          <Typography gutterBottom paragraph>
            Type: Persistent Cookies
          </Typography>
          <Typography gutterBottom paragraph>
            Administered by: the Company
          </Typography>
          <Typography gutterBottom paragraph>
            Purpose: These Cookies allow us to remember choices You make when
            You use the Website, such as remembering your login details or
            language preference. The purpose of these Cookies is to provide You
            with a more personal experience and to avoid You having to re-enter
            your preferences every time You use the Website.
          </Typography>
        </ListItem>
      </List>
      <Typography gutterBottom paragraph>
        For more information about the cookies we use and your choices regarding
        cookies, please visit our Cookies Policy or the Cookies section of our
        Privacy Policy.
      </Typography>
      <Typography
        component="h3"
        variant="h4"
        gutterBottom
        sx={{
          my: 5,
        }}
      >
        Use of Your Personal Data
      </Typography>
      <Typography gutterBottom paragraph>
        The Company may use Personal Data for the following purposes:
      </Typography>
      <List sx={{ listStyleType: "disc", pl: 5 }}>
        <ListItem sx={{ display: "list-item" }}>
          <strong>To provide and maintain our Service,</strong> including to
          monitor the usage of our Service.
        </ListItem>
        <ListItem sx={{ display: "list-item" }}>
          <strong>To manage Your Account: </strong> to manage Your registration
          as a user of the Service. The Personal Data You provide can give You
          access to different functionalities of the Service that are available
          to You as a registered user.
        </ListItem>
        <ListItem sx={{ display: "list-item" }}>
          <strong>For the performance of a contract:</strong> the development,
          compliance and undertaking of the purchase contract for the products,
          items or services You have purchased or of any other contract with Us
          through the Service.
        </ListItem>
        <ListItem sx={{ display: "list-item" }}>
          <strong>To contact You:</strong>To contact You by email, telephone
          calls, SMS, or other equivalent forms of electronic communication,
          such as a mobile application&apos;s push notifications regarding
          updates or informative communications related to the functionalities,
          products or contracted services, including the security updates, when
          necessary or reasonable for their implementation.
        </ListItem>
        <ListItem sx={{ display: "list-item" }}>
          <strong>To provide You</strong> with news, special offers and general
          information about other goods, services and events which we offer that
          are similar to those that you have already purchased or enquired about
          unless You have opted not to receive such information.
        </ListItem>
        <ListItem sx={{ display: "list-item" }}>
          <strong>To manage Your requests:</strong> To attend and manage Your
          requests to Us.
        </ListItem>
        <ListItem sx={{ display: "list-item" }}>
          <strong>For business transfers:</strong> We may use Your information
          to evaluate or conduct a merger, divestiture, restructuring,
          reorganization, dissolution, or other sale or transfer of some or all
          of Our assets, whether as a going concern or as part of bankruptcy,
          liquidation, or similar proceeding, in which Personal Data held by Us
          about our Service users is among the assets transferred.
        </ListItem>
        <ListItem sx={{ display: "list-item" }}>
          <strong>or other purposes:</strong> We may use Your information for
          other purposes, such as data analysis, identifying usage trends,
          determining the effectiveness of our promotional campaigns and to
          evaluate and improve our Service, products, services, marketing and
          your experience.
        </ListItem>
      </List>
      <Typography gutterBottom paragraph>
        We may share Your personal information in the following situations:
      </Typography>
      <List sx={{ listStyleType: "disc", pl: 5 }}>
        <ListItem sx={{ display: "list-item" }}>
          <strong>With Service Providers:</strong> We may share Your personal
          information with Service Providers to monitor and analyze the use of
          our Service, to contact You.
        </ListItem>
        <ListItem sx={{ display: "list-item" }}>
          <strong>For business transfers:</strong> We may share or transfer Your
          personal information in connection with, or during negotiations of,
          any merger, sale of Company assets, financing, or acquisition of all
          or a portion of Our business to another company.
        </ListItem>
        <ListItem sx={{ display: "list-item" }}>
          <strong>With Affiliates: </strong> We may share Your information with
          Our affiliates, in which case we will require those affiliates to
          honor this Privacy Policy. Affiliates include Our parent company and
          any other subsidiaries, joint venture partners or other companies that
          We control or that are under common control with Us.
        </ListItem>
        <ListItem sx={{ display: "list-item" }}>
          <strong>With business partners: </strong>We may share Your information
          with Our business partners to offer You certain products, services or
          promotions.
        </ListItem>
        <ListItem sx={{ display: "list-item" }}>
          <strong>With other users: </strong> when You share personal
          information or otherwise interact in the public areas with other
          users, such information may be viewed by all users and may be publicly
          distributed outside.
        </ListItem>
        <ListItem sx={{ display: "list-item" }}>
          <strong>With Your consent:</strong> TWe may disclose Your personal
          information for any other purpose with Your consent.
        </ListItem>
      </List>
      <Typography
        component="h3"
        variant="h4"
        gutterBottom
        sx={{
          my: 5,
        }}
      >
        Retention of Your Personal Data
      </Typography>
      <Typography gutterBottom paragraph>
        The Company will retain Your Personal Data only for as long as is
        necessary for the purposes set out in this Privacy Policy. We will
        retain and use Your Personal Data to the extent necessary to comply with
        our legal obligations (for example, if we are required to retain your
        data to comply with applicable laws), resolve disputes, and enforce our
        legal agreements and policies.
      </Typography>
      <Typography gutterBottom paragraph>
        The Company will also retain Usage Data for internal analysis purposes.
        Usage Data is generally retained for a shorter period of time, except
        when this data is used to strengthen the security or to improve the
        functionality of Our Service, or We are legally obligated to retain this
        data for longer time periods.
      </Typography>

      <Typography
        component="h3"
        variant="h4"
        gutterBottom
        sx={{
          my: 5,
        }}
      >
        Transfer of Your Personal Data
      </Typography>
      <Typography gutterBottom paragraph>
        Your information, including Personal Data, is processed at the
        Company&apos;s operating offices and in any other places where the
        parties involved in the processing are located. It means that this
        information may be transferred to — and maintained on — computers
        located outside of Your state, province, country or other governmental
        jurisdiction where the data protection laws may differ than those from
        Your jurisdiction.
      </Typography>
      <Typography gutterBottom paragraph>
        Your consent to this Privacy Policy followed by Your submission of such
        information represents Your agreement to that transfer.
      </Typography>
      <Typography gutterBottom paragraph>
        The Company will take all steps reasonably necessary to ensure that Your
        data is treated securely and in accordance with this Privacy Policy and
        no transfer of Your Personal Data will take place to an organization or
        a country unless there are adequate controls in place including the
        security of Your data and other personal information.
      </Typography>
      <Typography
        component="h3"
        variant="h4"
        gutterBottom
        sx={{
          my: 5,
        }}
      >
        Delete Your Personal Data
      </Typography>
      <Typography gutterBottom paragraph>
        You have the right to delete or request that We assist in deleting the
        Personal Data that We have collected about You.
      </Typography>
      <Typography gutterBottom paragraph>
        Our Service may give You the ability to delete certain information about
        You from within the Service.
      </Typography>
      <Typography gutterBottom paragraph>
        You may update, amend, or delete Your information at any time by signing
        in to Your Account, if you have one, and visiting the account settings
        section that allows you to manage Your personal information. You may
        also contact Us to request access to, correct, or delete any personal
        information that You have provided to Us.
      </Typography>
      <Typography gutterBottom paragraph>
        Please note, however, that We may need to retain certain information
        when we have a legal obligation or lawful basis to do so.
      </Typography>
      <Typography
        component="h3"
        variant="h4"
        gutterBottom
        sx={{
          my: 5,
        }}
      >
        Disclosure of Your Personal Data
      </Typography>
      <Typography component="h4" variant="h5" gutterBottom>
        Business Transactions
      </Typography>
      <Typography gutterBottom paragraph>
        If the Company is involved in a merger, acquisition or asset sale, Your
        Personal Data may be transferred. We will provide notice before Your
        Personal Data is transferred and becomes subject to a different Privacy
        Policy.
      </Typography>
      <Typography component="h4" variant="h5" gutterBottom sx={{ mt: 5 }}>
        Law enforcement
      </Typography>
      <Typography gutterBottom paragraph>
        Under certain circumstances, the Company may be required to disclose
        Your Personal Data if required to do so by law or in response to valid
        requests by public authorities (e.g. a court or a government agency).
      </Typography>
      <Typography component="h4" variant="h5" gutterBottom sx={{ mt: 5 }}>
        Other legal requirements
      </Typography>
      <Typography gutterBottom paragraph>
        The Company may disclose Your Personal Data in the good faith belief
        that such action is necessary to:
      </Typography>
      <List sx={{ listStyleType: "disc", pl: 5 }}>
        <ListItem sx={{ display: "list-item" }}>
          Comply with a legal obligation
        </ListItem>
        <ListItem sx={{ display: "list-item" }}>
          Protect and defend the rights or property of the Company
        </ListItem>
        <ListItem sx={{ display: "list-item" }}>
          Prevent or investigate possible wrongdoing in connection with the
          Service
        </ListItem>
        <ListItem sx={{ display: "list-item" }}>
          Protect the personal safety of Users of the Service or the public
        </ListItem>
        <ListItem sx={{ display: "list-item" }}>
          Protect against legal liability
        </ListItem>
      </List>
      <Typography
        component="h3"
        variant="h4"
        gutterBottom
        sx={{
          my: 5,
        }}
      >
        Security of Your Personal Data
      </Typography>
      <Typography gutterBottom paragraph>
        The security of Your Personal Data is important to Us, but remember that
        no method of transmission over the Internet, or method of electronic
        storage is 100% secure. While We strive to use commercially acceptable
        means to protect Your Personal Data, We cannot guarantee its absolute
        security.
      </Typography>
      <Typography
        component="h2"
        variant="h3"
        letterSpacing="-0.02em"
        gutterBottom
        sx={{
          mt: 7,
          mb: 5,
        }}
      >
        Children&apos;s Privacy
      </Typography>
      <Typography gutterBottom paragraph>
        Our Service does not address anyone under the age of 13. We do not
        knowingly collect personally identifiable information from anyone under
        the age of 13. If You are a parent or guardian and You are aware that
        Your child has provided Us with Personal Data, please contact Us. If We
        become aware that We have collected Personal Data from anyone under the
        age of 13 without verification of parental consent, We take steps to
        remove that information from Our servers.
      </Typography>
      <Typography gutterBottom paragraph>
        If We need to rely on consent as a legal basis for processing Your
        information and Your country requires consent from a parent, We may
        require Your parent&apos;s consent before We collect and use that
        information.
      </Typography>
      <Typography
        component="h2"
        variant="h3"
        letterSpacing="-0.02em"
        gutterBottom
        sx={{
          mt: 7,
          mb: 5,
        }}
      >
        Links to Other Websites
      </Typography>
      <Typography gutterBottom paragraph>
        Our Service may contain links to other websites that are not operated by
        Us. If You click on a third party link, You will be directed to that
        third party&apos;s site. We strongly advise You to review the Privacy
        Policy of every site You visit.
      </Typography>
      <Typography gutterBottom paragraph>
        We have no control over and assume no responsibility for the content,
        privacy policies or practices of any third party sites or services.
      </Typography>
      <Typography
        component="h2"
        variant="h3"
        letterSpacing="-0.02em"
        gutterBottom
        sx={{
          mt: 7,
          mb: 5,
        }}
      >
        Changes to this Privacy Policy
      </Typography>
      <Typography gutterBottom paragraph>
        We may update Our Privacy Policy from time to time. We will notify You
        of any changes by posting the new Privacy Policy on this page.
      </Typography>
      <Typography gutterBottom paragraph>
        We will let You know via email and/or a prominent notice on Our Service,
        prior to the change becoming effective and update the &quot;Last
        updated&quot; date at the top of this Privacy Policy.
      </Typography>
      <Typography gutterBottom paragraph>
        You are advised to review this Privacy Policy periodically for any
        changes. Changes to this Privacy Policy are effective when they are
        posted on this page.
      </Typography>
      <Typography
        component="h2"
        variant="h3"
        letterSpacing="-0.02em"
        gutterBottom
        sx={{
          mt: 7,
          mb: 5,
        }}
      >
        Contact Us
      </Typography>
      <Typography gutterBottom paragraph>
        If you have any questions about this Privacy Policy, You can contact us:
      </Typography>
      <List sx={{ listStyleType: "disc", pl: 5 }}>
        <ListItem sx={{ display: "list-item" }}>
          By email:{" "}
          <MuiLink
            target="_blank"
            rel="external noopener noreferrer"
            href="mailto:boilerplates@brocoders.com"
          >
            boilerplates@brocoders.com
          </MuiLink>
        </ListItem>
        <ListItem sx={{ display: "list-item" }}>
          By visiting this page on our website:{" "}
          <MuiLink
            target="_blank"
            rel="external noopener noreferrer"
            href="https://bcboilerplates.com/"
          >
            bc boilerplates
          </MuiLink>
        </ListItem>

        <ListItem sx={{ display: "list-item" }}>
          On Github Discussions for{" "}
          <MuiLink
            target="_blank"
            rel="external noopener noreferrer"
            href="https://github.com/brocoders/nestjs-boilerplate/discussions"
          >
            nestjs-boilerplate
          </MuiLink>{" "}
          or{" "}
          <MuiLink
            target="_blank"
            rel="external noopener noreferrer"
            href="https://github.com/brocoders/extensive-react-boilerplate/discussions"
          >
            extensive-react-boilerplate
          </MuiLink>
        </ListItem>
        <ListItem sx={{ display: "list-item" }}>
          On our{" "}
          <MuiLink
            target="_blank"
            rel="external noopener noreferrer"
            href="https://discord.com/channels/520622812742811698/1197293125434093701"
          >
            Discord channel
          </MuiLink>
        </ListItem>
      </List>
    </Container>
  );
}

export default PrivacyPolicy;
