export const SECTION_COMMON_PY = { xs: 4, sm: 5, md: 6 };
const BUY_NOW_URL = "";
export const FIGMA_LINK = {
  about: {
    link: BUY_NOW_URL,
    variant: {
      about1: BUY_NOW_URL,
      about2: BUY_NOW_URL,
      about3: BUY_NOW_URL,
    },
  },
  auth: {
    login: {
      link: BUY_NOW_URL,
      variant: {
        login1: BUY_NOW_URL,
        login2: BUY_NOW_URL,
        login3: BUY_NOW_URL,
        login4: BUY_NOW_URL,
        login5: BUY_NOW_URL,
      },
    },
    register: {
      link: BUY_NOW_URL,
    },
    forgotPassword: {
      link: BUY_NOW_URL,
    },
    newPassword: {
      link: BUY_NOW_URL,
    },
    otpVerification: {
      link: BUY_NOW_URL,
    },
  },
  benefit: {
    link: BUY_NOW_URL,
    variant: {
      benefit1: BUY_NOW_URL,
      benefit2: BUY_NOW_URL,
      benefit3: BUY_NOW_URL,
      benefit4: BUY_NOW_URL,
      benefit5: BUY_NOW_URL,
      benefit6: BUY_NOW_URL,
      benefit7: BUY_NOW_URL,
      benefit8: BUY_NOW_URL,
      benefit9: BUY_NOW_URL,
    },
  },
  blog: {
    link: BUY_NOW_URL,
    variant: {
      blog1: BUY_NOW_URL,
      blog2: BUY_NOW_URL,
      blog3: BUY_NOW_URL,
      blog4: BUY_NOW_URL,
      blog5: BUY_NOW_URL,
      blog6: BUY_NOW_URL,
    },
  },
  clientele: {
    link: BUY_NOW_URL,
    variant: {
      clientele1: BUY_NOW_URL,
      clientele2: BUY_NOW_URL,
      clientele3: BUY_NOW_URL,
      clientele4: BUY_NOW_URL,
      clientele5: BUY_NOW_URL,
      clientele6: BUY_NOW_URL,
      clientele7: BUY_NOW_URL,
    },
  },
  color: {
    link: BUY_NOW_URL,
  },
  cta: {
    link: BUY_NOW_URL,
    variant: {
      cta1: BUY_NOW_URL,
      cta2: BUY_NOW_URL,
      cta3: BUY_NOW_URL,
      cta4: BUY_NOW_URL,
      cta5: BUY_NOW_URL,
      cta6: BUY_NOW_URL,
      cta7: BUY_NOW_URL,
      cta8: BUY_NOW_URL,
      cta9: BUY_NOW_URL,
      cta10: BUY_NOW_URL,
      cta11: BUY_NOW_URL,
      cta12: BUY_NOW_URL,
    },
  },
  cookie: {
    link: BUY_NOW_URL,
    variant: {
      cookie1: BUY_NOW_URL,
      cookie2: BUY_NOW_URL,
      cookie3: BUY_NOW_URL,
    },
  },
  comingSoon: { link: BUY_NOW_URL },
  contactUs: {
    link: BUY_NOW_URL,
    variant: {
      contactUs1: BUY_NOW_URL,
      contactUs2: BUY_NOW_URL,
      contactUs3: BUY_NOW_URL,
      contactUs4: BUY_NOW_URL,
      contactUs5: BUY_NOW_URL,
      contactUs6: BUY_NOW_URL,
    },
  },
  error404: {
    link: BUY_NOW_URL,
  },
  error500: {
    link: BUY_NOW_URL,
  },
  earlyAccess: { link: BUY_NOW_URL },
  faq: {
    link: BUY_NOW_URL,
    variant: {
      faq1: BUY_NOW_URL,
      faq2: BUY_NOW_URL,
      faq3: BUY_NOW_URL,
      faq4: BUY_NOW_URL,
      faq5: BUY_NOW_URL,
      faq6: BUY_NOW_URL,
      faq7: BUY_NOW_URL,
    },
  },
  feature: {
    link: BUY_NOW_URL,
    variant: {
      feature1: BUY_NOW_URL,
      feature2: BUY_NOW_URL,
      feature3: BUY_NOW_URL,
      feature4: BUY_NOW_URL,
      feature5: BUY_NOW_URL,
      feature6: BUY_NOW_URL,
      feature7: BUY_NOW_URL,
      feature8: BUY_NOW_URL,
      feature9: BUY_NOW_URL,
      feature10: BUY_NOW_URL,
      feature11: BUY_NOW_URL,
      feature12: BUY_NOW_URL,
      feature13: BUY_NOW_URL,
      feature14: BUY_NOW_URL,
      feature15: BUY_NOW_URL,
      feature16: BUY_NOW_URL,
      feature17: BUY_NOW_URL,
      feature18: BUY_NOW_URL,
      feature19: BUY_NOW_URL,
      feature20: BUY_NOW_URL,
      feature21: BUY_NOW_URL,
      feature22: BUY_NOW_URL,
      feature23: BUY_NOW_URL,
    },
  },
  footer: {
    link: BUY_NOW_URL,
    variant: {
      footer1: BUY_NOW_URL,
      footer2: BUY_NOW_URL,
      footer3: BUY_NOW_URL,
      footer4: BUY_NOW_URL,
      footer5: BUY_NOW_URL,
      footer6: BUY_NOW_URL,
      footer7: BUY_NOW_URL,
    },
  },
  gallery: {
    link: BUY_NOW_URL,
    variant: {
      gallery1: BUY_NOW_URL,
      gallery2: BUY_NOW_URL,
      gallery3: BUY_NOW_URL,
      gallery4: BUY_NOW_URL,
    },
  },
  hero: {
    link: BUY_NOW_URL,
    variant: {
      hero1: BUY_NOW_URL,
      hero2: BUY_NOW_URL,
      hero3: BUY_NOW_URL,
      hero4: BUY_NOW_URL,
      hero5: BUY_NOW_URL,
      hero6: BUY_NOW_URL,
      hero7: BUY_NOW_URL,
      hero8: BUY_NOW_URL,
      hero9: BUY_NOW_URL,
      hero10: BUY_NOW_URL,
      hero11: BUY_NOW_URL,
      hero12: BUY_NOW_URL,
      hero13: BUY_NOW_URL,
      hero14: BUY_NOW_URL,
      hero15: BUY_NOW_URL,
      hero16: BUY_NOW_URL,
      hero17: BUY_NOW_URL,
    },
  },
  icon: {
    link: BUY_NOW_URL,
  },
  integration: {
    link: BUY_NOW_URL,
    variant: {
      integration1: BUY_NOW_URL,
      integration2: BUY_NOW_URL,
      integration3: BUY_NOW_URL,
      integration4: BUY_NOW_URL,
      integration5: BUY_NOW_URL,
      integration6: BUY_NOW_URL,
      integration7: BUY_NOW_URL,
      integration8: BUY_NOW_URL,
    },
  },
  megamenu: {
    link: BUY_NOW_URL,
    variant: {
      megamenu1: BUY_NOW_URL,
      megamenu2: BUY_NOW_URL,
      megamenu3: BUY_NOW_URL,
      megamenu4: BUY_NOW_URL,
      megamenu5: BUY_NOW_URL,
    },
  },
  navbar: {
    link: BUY_NOW_URL,
    variant: {
      navbar1: BUY_NOW_URL,
      navbar2: BUY_NOW_URL,
      navbar3: BUY_NOW_URL,
      navbar4: BUY_NOW_URL,
      navbar5: BUY_NOW_URL,
      navbar6: BUY_NOW_URL,
      navbar7: BUY_NOW_URL,
      navbar8: BUY_NOW_URL,
      navbar9: BUY_NOW_URL,
      navbar10: BUY_NOW_URL,
    },
  },
  onboard: { link: BUY_NOW_URL },
  other: {
    link: BUY_NOW_URL,
    variant: {
      other1: BUY_NOW_URL,
      other2: BUY_NOW_URL,
      other3: BUY_NOW_URL,
    },
  },
  pricing: {
    link: BUY_NOW_URL,
    variant: {
      pricing1: BUY_NOW_URL,
      pricing2: BUY_NOW_URL,
      pricing3: BUY_NOW_URL,
      pricing4: BUY_NOW_URL,
      pricing5: BUY_NOW_URL,
      pricing6: BUY_NOW_URL,
      pricing7: BUY_NOW_URL,
      pricing8: BUY_NOW_URL,
      pricing9: BUY_NOW_URL,
    },
  },
  process: {
    link: BUY_NOW_URL,
    variant: {
      process1: BUY_NOW_URL,
      process2: BUY_NOW_URL,
      process3: BUY_NOW_URL,
      process4: BUY_NOW_URL,
      process5: BUY_NOW_URL,
      process6: BUY_NOW_URL,
      process7: BUY_NOW_URL,
    },
  },
  privacyPolicy: { link: BUY_NOW_URL },
  smallHero: {
    link: BUY_NOW_URL,
    variant: {
      smallHero1: BUY_NOW_URL,
      smallHero2: BUY_NOW_URL,
      smallHero3: BUY_NOW_URL,
      smallHero4: BUY_NOW_URL,
      smallHero5: BUY_NOW_URL,
      smallHero6: BUY_NOW_URL,
      smallHero7: BUY_NOW_URL,
    },
  },
  team: {
    link: BUY_NOW_URL,
    variant: {
      team1: BUY_NOW_URL,
      team2: BUY_NOW_URL,
      team3: BUY_NOW_URL,
      team4: BUY_NOW_URL,
      team5: BUY_NOW_URL,
      team6: BUY_NOW_URL,
      team7: BUY_NOW_URL,
      team8: BUY_NOW_URL,
    },
  },
  testimonial: {
    link: BUY_NOW_URL,
    variant: {
      testimonial1: BUY_NOW_URL,
      testimonial2: BUY_NOW_URL,
      testimonial3: BUY_NOW_URL,
      testimonial4: BUY_NOW_URL,
      testimonial5: BUY_NOW_URL,
      testimonial6: BUY_NOW_URL,
      testimonial7: BUY_NOW_URL,
      testimonial8: BUY_NOW_URL,
      testimonial9: BUY_NOW_URL,
      testimonial10: BUY_NOW_URL,
      testimonial11: BUY_NOW_URL,
    },
  },
  termsCondition: { link: BUY_NOW_URL },
  topOffer: {
    link: BUY_NOW_URL,
    variant: {
      topOffer1: BUY_NOW_URL,
      topOffer2: BUY_NOW_URL,
      topOffer3: BUY_NOW_URL,
      topOffer4: BUY_NOW_URL,
      topOffer5: BUY_NOW_URL,
    },
  },
  typography: {
    link: BUY_NOW_URL,
  },
  underMaintenance: {
    link: BUY_NOW_URL,
  },
};
